### ISSUE TITLE
Can you release your code of latentkeypointgan?

### ISSUE THREAD

**Issue by Lifedecoder** [xingzhehe/LatentKeypointGAN#1]
Hi Xingzhe!

It's quite novel of your work about latentkeypointgan. I've read about your paper but it seems that many details are not shown in paper. Like how the keypoints become constant embedding? Or what's the specific form they have? Or by what ways they can be identified compared with other keypoints who also have some constant embeddings? 
Hope that you could give some explanations, and it will be more great if you can release the code of this work! 

Thanks!
Leo

**Comment by xingzhehe** [comment]
Hi Leo,

Thanks for your interest. I am sorry that I cannot release the code since it has not been officially published. 
However, one of the follow-up work, GANSeg, shares a very similar architecture. You can check it out:
https://github.com/xingzhehe/GANSeg

Bests!
Xingzhe

**Comment by Lifedecoder** [comment]
OK, got that, thanks!
